version: '3'
services:
  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    ports:
      - "7000:7000"
    networks:
      - "flamingo-network"
  customer-service:
    build: ./customer-service
    container_name: customer-service
    networks:
      - "flamingo-network"
  email-service:
    build: ./email-service
    container_name: email-service
    networks:
      - "flamingo-network"
  log-service:
    build: ./log-service
    container_name: log-service
    networks:
      - "flamingo-network"
  order-service:
    build: ./order-service
    container_name: order-service
    networks:
      - "flamingo-network"
  customer-db:
    image: postgres
    container_name: customer-db
    environment:
      - POSTGRES_PASSWORD: Abc.12345
      - POSTGRES_DB: customer_db
    networks:
      - "flamingo-network"
  order-db:
    image: mongo
    container_name: order-db
    networks:
      - "flamingo-network"
networks:
  flamingo-network:
    driver: bridge